name: Build CLI tool

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install native dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libpcsclite-dev
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies (root)
        run: |
          npm --include=dev install
      - name: Install dependencies (cli)
        run: |
          cd cli
          npm --include=dev install
      - name: Package HaLo CLI tool
        run: |
          cd cli
          node_modules/.bin/pkg package.json
      - name: Upload artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: halo-cli-binaries
          path: cli/dist/*
