name: Build halocli tool

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'cli/README.md'
      - 'docs/**'
    branches:
      - master
    tags:
      - 'halocli-v*'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'cli/README.md'
      - 'docs/**'
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare version number
        id: parse_version
        run: |
          ( echo -n "version=" && ( echo "$GITHUB_REF" | cut -f2 -d- | tr -d '\n' ) ) >> "$GITHUB_OUTPUT"
      - name: Draft release
        id: create_release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/halocli-v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: HaLo CLI ${{ steps.parse_version.outputs.version }}
          draft: true
          prerelease: false
          body: |
            Standalone command line tool for desktop computers with PC/SC readers (USB/NFC readers).
            
            Release contents:
            * `halocli-linux-x64.zip` - Linux x64 build (elf; zipped)
            * `halocli-win-x64.zip` - Windows 64 build (exe; zipped)
            * `halocli-macos-x64.pkg` - MacOS x64 build (installer; signed)
      - name: Store release upload URL
        if: startsWith(github.ref, 'refs/tags/halocli-v')
        run: |
          echo -n "${{ steps.create_release.outputs.upload_url }}" > release-upload-url.txt
      - uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/halocli-v')
        with:
          name: release-upload-url
          path: release-upload-url.txt

  build_cli_tool:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            bin_name: halocli-linux-x64.zip
          - os: windows-latest
            bin_name: halocli-win-x64.zip
          - os: macos-latest
            bin_name: halocli-macos-x64.pkg
    runs-on: ${{ matrix.os }}
    needs: create_release
    steps:
      - name: Install native dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y libpcsclite-dev
      - name: Install native dependencies (MacOS)
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/halocli-v')
        run: |
          brew install pcsc-lite
      - name: Import codesign certificates for application (Mac OS)
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/halocli-v')
        uses: apple-actions/import-codesign-certs@253ddeeac23f2bdad1646faac5c8c2832e800071
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATES_P12 }}
          p12-password: ${{ secrets.MACOS_CERTIFICATES_P12_PASSWORD }}
      - name: Checkout the repository
        if: github.event_name != 'pull_request' || matrix.os == 'ubuntu-latest'
        uses: actions/checkout@v3
      - name: Load code signing certificate (Windows)
        if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/halocli-v')
        uses: timheuer/base64-to-file@48657ba25c726c2e3dcf02efa3639fff9b3d587e
        with:
          fileName: authenticode.p12
          fileDir: ${{ env.RUNNER_TEMP }}
          encodedString: ${{ secrets.WINDOWS_AUTHENTICODE_P12 }}
      - name: Install Node.JS
        if: github.event_name != 'pull_request' || matrix.os == 'ubuntu-latest'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies (root)
        if: github.event_name != 'pull_request' || matrix.os == 'ubuntu-latest'
        run: |
          npm --include=dev install
      - name: Install dependencies (cli)
        if: github.event_name != 'pull_request' || matrix.os == 'ubuntu-latest'
        run: |
          cd cli
          npm --include=dev install
      - name: Package HaLo CLI tool (Linux)
        if: github.event_name != 'pull_request' && matrix.os == 'ubuntu-latest'
        run: |
          cd cli
          node_modules/.bin/pkg -t node16-linux-x64 package.json
      - name: Compress application (Linux)
        if: github.event_name != 'pull_request' && matrix.os == 'ubuntu-latest'
        run: |
          cd ./cli/dist
          zip halocli-linux-x64.zip halocli
      - name: Package HaLo CLI tool (Windows)
        if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/halocli-v')
        run: |
          cd cli
          node_modules/.bin/pkg -t node16-win-x64 package.json
      - name: Package HaLo CLI tool (MacOS)
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/halocli-v')
        run: |
          cd cli
          node_modules/.bin/pkg -t node16-macos-x64 package.json
      - name: Sign application for Windows
        if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/halocli-v')
        run: |
          & "C:/Program Files (x86)/Windows Kits/10/App Certification Kit/signtool.exe" sign /v /fd SHA256 /f "${{ env.RUNNER_TEMP }}/authenticode.p12" /t http://timestamp.sectigo.com "./cli/dist/halocli.exe"
      - name: Compress application (Windows)
        if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/halocli-v')
        run: |
          cd ./cli/dist
          Compress-Archive halocli.exe halocli-win-x64.zip
      - name: Sign application for Mac OS
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/halocli-v')
        run: |
          mkdir -p cli/dist/root/usr/local/bin/
          mv cli/dist/halocli cli/dist/root/usr/local/bin/halocli
          /usr/bin/codesign --deep --force --options=runtime --entitlements ./cli/Entitlements.plist --sign "${{ secrets.MACOS_IDENTITY }}" --timestamp ./cli/dist/root/usr/local/bin/halocli
          pkgbuild --root ./cli/dist/root --identifier "org.arx.halo.halocli" --version "1.0.$(date +%s)" --install-location "/" --sign "${{ secrets.MACOS_IDENTITY_INSTALLER }}" ./cli/dist/halocli-macos-x64.pkg
      - name: Notarize application for Mac OS
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/halocli-v')
        run: |
          xcrun notarytool submit "--apple-id=${{ secrets.MACOS_APPLE_ID }}" "--password=${{ secrets.MACOS_PWD_ALTOOL }}" "--team-id=${{ secrets.MACOS_TEAM_ID }}" --progress --wait ./cli/dist/halocli-macos-x64.pkg
      - name: Staple notarized application for Mac OS
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/halocli-v')
        run: |
          xcrun stapler staple -v ./cli/dist/halocli-macos-x64.pkg
          rm -rf ./cli/dist/root/
      - name: Download release upload URL
        if: startsWith(github.ref, 'refs/tags/halocli-v')
        uses: actions/download-artifact@v2
        with:
          name: release-upload-url
      - name: Store release upload URL output
        id: out_store
        if: startsWith(github.ref, 'refs/tags/halocli-v')
        shell: bash
        run: |
          echo "release_upload_url=$(cat release-upload-url.txt)" >> "$GITHUB_OUTPUT"
      - name: Upload release asset
        id: upload-release-asset
        if: startsWith(github.ref, 'refs/tags/halocli-v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.out_store.outputs.release_upload_url }}
          asset_path: ./cli/dist/${{ matrix.bin_name }}
          asset_name: ${{ matrix.bin_name }}
          asset_content_type: application/octet-stream
