name: Build CLI tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies (root)
        run: |
          npm --include=dev install
      - name: Install dependencies (cli)
        run: |
          cd cli
          npm --include=dev install
      - name: Package HaLo CLI tool
        run: |
          cd cli
          pkg package.json
