name: Check libhalo package

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'cli/README.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'cli/README.md'
      - 'docs/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Run npm ci
        run: npm ci
