name: Check halocli tool

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'cli/README.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'cli/README.md'
      - 'docs/**'
    branches:
      - master

jobs:
  check_cli_tool:
    runs-on: ubuntu-latest
    steps:
      - name: Install native dependencies (Linux)
        run: |
          sudo apt-get update && sudo apt-get install -y libpcsclite-dev
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies (root)
        run: |
          yarn install --frozen-lockfile --production=false
      - name: Install dependencies (cli)
        run: |
          cd cli
          yarn install --frozen-lockfile --production=false
      - name: Package HaLo CLI tool (Linux)
        run: |
          cd cli
          node_modules/.bin/pkg -t node18-linux-x64 package.json
