name: Integrity check

on: [push]

jobs:
  test_check:
    name: Integrity check
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@c3667d99424e7e6047999fb6246c0da843953c65
      - name: Get latest version from npm
        id: get-latest-npm
        run: |
          curl -s https://registry.npmjs.org/@arx-research/libhalo/latest > "$RUNNER_TEMP/package-npm.json"
          NPM_LATEST_VER=$(cat "$RUNNER_TEMP/package-npm.json" | jq --raw-output '.version' | tr -d '\n')
          NPM_HASH=$(cat "$RUNNER_TEMP/package-npm.json" | jq --raw-output '.dist.integrity' | tr -d '\n')
          echo "NPM_LATEST_VER=$NPM_LATEST_VER" >> $GITHUB_ENV
          echo "NPM_HASH=$NPM_HASH" >> $GITHUB_ENV
      - name: Check cosign signature
        run: |
          NPM_LATEST_VER=${{ steps.get-latest-npm.outputs.NPM_LATEST_VER }}
          curl -s -o "$RUNNER_TEMP/libhalo-npm-hash.txt" "https://github.com/arx-research/libhalo/releases/download/libhalo-v${NPM_LATEST_VER}/libhalo-npm-hash.txt"
          curl -s -o "$RUNNER_TEMP/libhalo-npm-hash.txt-keyless.pem" "https://github.com/arx-research/libhalo/releases/download/libhalo-v${NPM_LATEST_VER}/libhalo-npm-hash.txt-keyless.pem"
          curl -s -o "$RUNNER_TEMP/libhalo-npm-hash.txt-keyless.sig" "https://github.com/arx-research/libhalo/releases/download/libhalo-v${NPM_LATEST_VER}/libhalo-npm-hash.txt-keyless.sig"
          cosign verify-blob \
            --cert "$RUNNER_TEMP/libhalo-npm-hash.txt-keyless.pem" \
            --signature "$RUNNER_TEMP/libhalo-npm-hash.txt-keyless.sig" \
            --certificate-identity "https://github.com/arx-research/libhalo/.github/workflows/prod_build_lib.yml@refs/tags/libhalo-v${NPM_LATEST_VER}" \
            --certificate-oidc-issuer https://token.actions.githubusercontent.com \
            "$RUNNER_TEMP/libhalo-npm-hash.txt"
      - name: Verify integrity hash on npmjs
        run: |
          NPM_HASH=${{ steps.get-latest-npm.outputs.NPM_HASH }}
          OUR_HASH=$(cat "$RUNNER_TEMP/libhalo-npm-hash.txt" | tr -d '\n')
          [[ "$NPM_HASH" == "$OUR_HASH" ]]
