name: Publish libhalo package

on:
  push:
    tags:
      - 'libhalo-v*'

jobs:
  build:
    name: Publish libhalo package
    environment: prod-npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Run npm ci
        run: npm ci
      - name: Publish package to npmjs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RELEASE_NPM_TOKEN }}
      - name: Re-setup Node.JS with GitHub pkg
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
      - name: Publish package to GitHub
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
