name: Integrity check

on: [push]

jobs:
  test_check:
    name: Integrity check
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - run: |
          curl -s https://registry.npmjs.org/@arx-research/libhalo/latest | jq --raw-output '.dist.integrity' | tr -d '\n'
      - run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/ORG/packages/PACKAGE_TYPE/PACKAGE_NAME/versions/PACKAGE_VERSION_ID
