name: Publish libhalo package

on:
  push:
    branches:
      - '*'
    tags:
      - 'libhalo-v*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Publish package to npmjs
        run: npm publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/libhalo-v')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Resetup Node.JS with GitHub pkg
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
      - name: Publish package to GitHub
        run: npm publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/libhalo-v')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
